MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.004
  WEIGHT_DECAY: 0.0001
  STEPS: (12500, )
  MAX_ITER: 91750000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 10000
INPUT: 
  SEMI: True
TEST:
  IMS_PER_BATCH: 4
SEMI:
  EMA_DECAY: 0.99
  TEMPORAL_NUM: 10
  TEMPORAL_SAVE_PATH:
  
OUTPUT_DIR:
  